version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0"
    depends_on:
      - postgresql
    env_file:
      - ./.env
  
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data

  postgresql-test:
    image: postgres
    ports:
      - 5434:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./.env
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - postgresql
